name: Build the app and run the tests

on:
  push:
    branches: [ "feature", "develop" ]

jobs:
  build_and_testing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build the application
      run: dotnet build --no-restore
      
    - name: Start the Unit tests
      run: dotnet test SoftUniBazar.Tests --no-build --verbosity normal
    - name: Start the Integration tests
      run: dotnet test SoftUniBazar.IntegrationTests --no-build --verbosity normal
